spring:
  jpa:
    properties:
      # Migrations generation config
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: src/main/resources/db/changelog/changes/V1__init_schema.sql # generate V1 of the datbase