create table appointments
(
    doctor_id    integer,
    id           integer generated by default as identity,
    patient_id   integer,
    status       varchar(255) not null,
    time_slot_id integer unique,
    sheduled_at  timestamp(6),
    reason       varchar(255),
    primary key (id)
);
create table doctors_profiles
(
    consultation_fee numeric(38, 2) not null,
    doctor_id        integer unique,
    id               integer generated by default as identity,
    speciality       varchar(100)   not null,
    bio              varchar(255),
    primary key (id)
);
create table medical_records
(
    appointment_id integer unique,
    id             integer generated by default as identity,
    diagnosis      varchar(255) not null,
    notes          varchar(255),
    prescription   varchar(255) not null,
    primary key (id)
);
create table time_slots
(
    doctor_id    integer,
    id           integer generated by default as identity,
    is_available boolean not null,
    end_time     timestamp(6),
    start_time   timestamp(6),
    primary key (id)
);
create table users
(
    id         integer generated by default as identity,
    role       varchar(255) not null,
    email      varchar(50)  not null,
    first_name varchar(50)  not null,
    password   varchar(255) not null,
    primary key (id)
);
alter table if exists appointments
    add constraint FK6u6s6egu60m2cbdjno44jbipa foreign key (doctor_id) references users;
alter table if exists appointments
    add constraint FKopb2h9yhin1rb4dqote8bws6w foreign key (patient_id) references users;
alter table if exists appointments
    add constraint FKlt1cehvx9m01l4s0ibvx60xv1 foreign key (time_slot_id) references time_slots;
alter table if exists doctors_profiles
    add constraint FK7cvr0n5jy9gusp9syspbe5y6o foreign key (doctor_id) references users;
alter table if exists medical_records
    add constraint FKifeec8p5v06rt258odelw8s7j foreign key (appointment_id) references appointments;
alter table if exists time_slots
    add constraint FKultmvjxpd6kbw8o3hej2v992 foreign key (doctor_id) references users;

